### ISSUE TITLE
Some apps don't detect phone model correctly

### ISSUE THREAD

**Issue by ghost** [crdroidandroid/device_xiaomi_surya#2]
Hello @GtrCraft and sorry for my bad english.

In the russian 4pda community I found a screenshot of a user with the results of the geekbench5 and decided to compare his result on miui and my on crdroid
But I noticed that the benchmark incorrectly determines the device model, which can be seen in my screenshot.
If I understand correctly this may be a problem in the device tree configs

https://play.google.com/store/apps/details?id=com.primatelabs.geekbench5

This is what I foud in miui thread on 4pda community
![Screenshot_2022-06-18-02-10-52-281_com miui home](https://user-images.githubusercontent.com/31875619/174444139-35a9392f-2cc5-45bf-a83b-a7221d1a1ca2.png)

And this is mine
![Screenshot_20220618-180534_Geekbench 5](https://user-images.githubusercontent.com/31875619/174444418-52728111-8975-428e-9c88-dd7e07fdd7f4.png)

P.S.
It is worth paying tribute to the crDroid rom, it turned out to be faster than miui even in benchmark

**Comment by GtrCraft** [comment]
If I change it back to POCO X3 NFC, Netflix and other video apps won't have full resolution or hdr.
So I will keep it like this.
