### ISSUE TITLE
Alarm clock does not turn on the screen

### ISSUE THREAD

**Issue by ghost** [crdroidandroid/device_xiaomi_surya#5]
Hi.

Every morning I see this behavior of the alarm clock:

0. First of all I hear a default notification sound
1. Phone display does not turn on when alarm is triggered
2. Deskclock app can't get through the screen lock like the dialer app does when there is an incoming call
3. I have to wake up and unlock my phone then tap on the notification to finaly see a working alarm

All Deskclock app permissions are granted
My device
https://github.com/crdroidandroid/android_device_xiaomi_surya

Video demonstration
https://drive.google.com/file/d/1whDN_yLchXQzhStybCCp0AJaX5dpc4vu/view

**Comment by gwolf2u** [comment]
@GtrCraft can you confirm?

**Comment by ghost** [comment]
Problem is still present in new 23/08 build.

**Comment by GtrCraft** [comment]
Works fine here with google clock, try to use that
