### ISSUE TITLE
Refresh Rate per-app wrong values in list

### ISSUE THREAD

**Issue by ghost** [crdroidandroid/device_xiaomi_surya#6]
Hi

After switching to Silont kernel, list of available refresh rate modes in Settings => Display => *refresh rate looks like 60, 75, 90, 120

However, the Refresh Rate per-app in list is hardcoded and does not change dynamically depending on the kernel
It is still has 30, 60, 90, 120 and does not work correctly
https://github.com/crdroidandroid/android_device_xiaomi_surya/blob/3e20df9d12c54622d14ca456618d08482072fb5a/parts/src/org/lineageos/settings/refreshrate/RefreshUtils.java#L45-L49

**Comment by gwolf2u** [comment]
maintainer is using proper kernel for said functionality

**Comment by ghost** [comment]
I did not say that kernel is not proper.

I said that Refresh Rate per-app setting does not work correctly with the values set in kernel because of another values hardcoded in it.

**Comment by GtrCraft** [comment]
Some kernels have 30hz so I left it in
