### ISSUE TITLE
help  just a question

### ISSUE THREAD

**Issue by powl999** [crdroidandroid/device_xiaomi_surya#9]
Now building surya-ap1a-nowhere.com
In file included from build/make/core/config.mk:389:
In file included from build/make/core/envsetup.mk:350:
build/make/core/product_config.mk:226: error: Cannot locate config makefile for product "lineage_surya".
15:03:04 dumpvars failed with: exit status 1
/usr/bin/env: 'python': No such file or directory
In file included from build/make/core/config.mk:389:
In file included from build/make/core/envsetup.mk:350:
build/make/core/product_config.mk:226: error: Cannot locate config makefile for product "lineage_surya".
15:03:04 dumpvars failed with: exit status 1
In file included from build/make/core/config.mk:389:
In file included from build/make/core/envsetup.mk:350:
build/make/core/product_config.mk:226: error: Cannot locate config makefile for product "lineage_surya".
15:03:05 dumpvars failed with: exit status 1

** Don't have a product spec for: 'lineage_surya'
** Do you have the right repo manifest?

In file included from build/make/core/config.mk:389:
In file included from build/make/core/envsetup.mk:51:
build/make/core/release_config.mk:100: error: No release config set for target; please set TARGET_RELEASE, or if building on the command line use 'lunch <target>-<release>-<build_type>', where release is one of: ap1a.
15:03:05 dumpvars failed with: exit status 1

i used these instructions https://github.com/crdroidandroid/android 
and this from the auto builder plaese help my i dont understand how to buil it my self 

s this correct [y/N]? y

repo has been initialized in /home/paul/crDroid
paul@linux:~/crDroid> brunch surya
 brunch: command not found
paul@linux:~/crDroid> . build/envsetup.sh
ccache directory found, CCACHE_DIR set to: /home/paul/.ccache
Set cache size limit to 40.0 GB
ccache enabled, CCACHE_EXEC set to: /usr/bin/ccache, CCACHE_MAXSIZE set to: 40G, direct_mode set to: false
Current ccache size is: 4.0K
paul@linux:~/crDroid> brunch surya
In file included from build/make/core/config.mk:389:
In file included from build/make/core/envsetup.mk:350:
build/make/core/product_config.mk:226: error: Cannot locate config makefile for product "lineage_surya".
15:13:51 dumpvars failed with: exit status 1
/usr/bin/env: ‘python’: No such file or directory
In file included from build/make/core/config.mk:389:
In file included from build/make/core/envsetup.mk:350:
build/make/core/product_config.mk:226: error: Cannot locate config makefile for product "lineage_surya".
15:13:52 dumpvars failed with: exit status 1
In file included from build/make/core/config.mk:389:
In file included from build/make/core/envsetup.mk:350:
build/make/core/product_config.mk:226: error: Cannot locate config makefile for product "lineage_surya".
15:13:52 dumpvars failed with: exit status 1

** Don't have a product spec for: 'lineage_surya'
** Do you have the right repo manifest?

No such item in brunch menu. Try 'breakfast'
paul@linux:~/crDroid> brunch karna
In file included from build/make/core/config.mk:389:
In file included from build/make/core/envsetup.mk:350:
build/make/core/product_config.mk:226: error: Cannot locate config makefile for product "lineage_karna".
15:13:59 dumpvars failed with: exit status 1
/usr/bin/env: ‘python’: No such file or directory
In file included from build/make/core/config.mk:389:
In file included from build/make/core/envsetup.mk:350:
build/make/core/product_config.mk:226: error: Cannot locate config makefile for product "lineage_karna".
15:14:00 dumpvars failed with: exit status 1
In file included from build/make/core/config.mk:389:
In file included from build/make/core/envsetup.mk:350:
build/make/core/product_config.mk:226: error: Cannot locate config makefile for product "lineage_karna".
15:14:00 dumpvars failed with: exit status 1

** Don't have a product spec for: 'lineage_karna'
** Do you have the right repo manifest?

No such item in brunch menu. Try 'breakfast'
paul@linux:~/crDroid> brunch breakfast
In file included from build/make/core/config.mk:389:
In file included from build/make/core/envsetup.mk:350:
build/make/core/product_config.mk:226: error: Cannot locate config makefile for product "lineage_breakfast".
15:14:15 dumpvars failed with: exit status 1
/usr/bin/env: ‘python’: No such file or directory
In file included from build/make/core/config.mk:389:
In file included from build/make/core/envsetup.mk:350:
build/make/core/product_config.mk:226: error: Cannot locate config makefile for product "lineage_breakfast".
15:14:15 dumpvars failed with: exit status 1
In file included from build/make/core/config.mk:389:
In file included from build/make/core/envsetup.mk:350:
build/make/core/product_config.mk:226: error: Cannot locate config makefile for product "lineage_breakfast".
15:14:16 dumpvars failed with: exit status 1

** Don't have a product spec for: 'lineage_breakfast'
** Do you have the right repo manifest?

No such item in brunch menu. Try 'breakfast'
paul@linux:~/crDroid> 

please help

**Comment by gwolf2u** [comment]
https://github.com/crdroidandroid/android/commit/de319a4b168734f8288defc721efeae0273e1b46
also please use issue_tracker in the future
